"""SADAR-merge (Direction C) — LLM analysis-report generator (OFFLINE / build-time).

An LLM-as-component **explainer** (NOT the detector): given the structured facts the
AE already computed for a case (score, percentile, band, per-feature attribution, channel
summaries, and our data-quality flags), it writes a short forensic-conformance note on
*what drove the reconstruction error* — and, crucially, says plainly when the "anomaly"
is a data/gate artifact rather than behaviour (D-014).

Generated at BUILD time by `precompute.py` (key local), baked into the bundle, served as
static text. So there is NO API key, no paid endpoint, no latency, and no cost/abuse
surface on the public Space (plan-eng-review + codex outside-voice, 2026-06-04). It never
affects the score or the Phase-7 eval.

Config knobs:
  - SYSTEM_PROMPT below (edit it → re-run precompute → reports regenerate for changed prompt)
  - ANTHROPIC_MODEL env (default claude-sonnet-4-6) so a model rename can't break the build
"""
from __future__ import annotations

import hashlib
import json
import os
import re

from backend.serve.quality import assessment_copy

DEFAULT_MODEL = "claude-sonnet-4-6"
# Reports are generated by Claude Code subagents (free on the CC plan) via a Workflow, not the
# metered Anthropic API. This label is the cache/model tag (keeps generation free).
SUBAGENT_LABEL = "claude-code-subagent"
MAX_TOKENS = 700

# ── the configurable system prompt ─────────────────────────────────────────────────────────
# Tightened per the codex outside-voice: narrate ONLY the observed fields, rank the evidence,
# and forbid not just "drone" but any implied intent / violation / aircraft identity /
# operational causality. Plain text (rendered verbatim, no markup).
SYSTEM_PROMPT = """\
You are a flight-conformance analyst writing a SHORT, SCANNABLE forensic note for an \
air-traffic data review tool, about ONE completed flight segment near Madrid-Barajas (LEMD). \
You are given the structured facts a trajectory anomaly model (an LSTM autoencoder) already \
computed. Explain WHAT DROVE THE RECONSTRUCTION-ERROR SCORE — nothing more.

OUTPUT FORMAT — plain text only (NO markdown, no **bold**, no # headings, no code fences). \
Emit EXACTLY this structure:

<CATEGORY in caps> · <flagged | not flagged> · <N>th percentile
RE <score> — <multiple>x the <threshold> threshold (per-step peak <peak>). <ONE short clause \
describing whether the evidence is reviewable or the system must abstain.>

What drove the score
• <channel> (<attr>) — <one short clause on the behaviour it captures, from the channel summaries>
• <channel> (<attr>) — <one short clause>
• <channel> (<attr>) — <one short clause>
(3 to 4 bullets, dominant channels first)

Reading
<1-2 short sentences: what the pattern means in plain language.>

RULES:
- Use ONLY the provided fields. Never invent numbers, callsigns, aircraft types, routes, or \
events. If unknown, say so.
- The assessment_state, behavioral_verdict, data_quality_flags, and assessment_explanation \
fields are authoritative. If behavioral_verdict is not_assessable, state the observed conflict \
and that analyst review is required. Never assign a cause (sensor error, ingestion, spoofing, \
or behavior). If reviewable, call it model evidence for analyst review, never a genuine anomaly.
- Behavioural conformance, NOT threat assessment. Never assert or imply a drone/UAV, intruder, \
unauthorized flight, airspace violation, intent, danger, aircraft identity, or a definite cause.
- The threshold is frozen; never suggest retuning it.
- Output ONLY the note: no preamble ("Here is..."), no sign-off, no markdown. ~90-130 words."""


def prompt_fingerprint(model: str) -> str:
    """8-hex digest of (system prompt + model) — the cache key so a prompt/model edit
    invalidates only the affected baked reports on the next precompute run."""
    return hashlib.sha1(f"{SYSTEM_PROMPT}\n{model}".encode()).hexdigest()[:8]


# ── deterministic data-quality classification (label, not LLM-inferred) ─────────────────────

def classify(case: dict) -> str:
    """Narratable assessment from deterministic fields; never assigns behavior or cause."""
    return assessment_copy(case)


def abstention_report(case: dict, threshold: float) -> str:
    multiple = float(case.get("score", 0.0)) / max(threshold, 1e-12)
    flags = ", ".join(case.get("data_quality_flags", [])) or "coverage limitation"
    return (
        f"{case.get('label', 'normal').upper()} · "
        f"{'flagged' if case.get('anomalous') else 'not flagged'} · "
        f"{round(float(case.get('pct', 0)))}th percentile\n"
        f"RE {float(case.get('score', 0)):.3f} — {multiple:.1f}x the {threshold} threshold. "
        "Raw model output retained.\n\n"
        "Assessment\n"
        f"{assessment_copy(case)}\n\n"
        "Observed guardrails\n"
        f"• {flags}\n"
        f"• maximum altitude jump: {float(case.get('max_altitude_jump_m', 0)):.1f} m\n"
        f"• observed steps: {int(case.get('valid_steps', 0))} "
        f"({float(case.get('observed_fraction', 0)) * 100:.1f}% coverage)\n\n"
        "Analyst action\n"
        "Review source telemetry and corroborating evidence. The system does not assign a "
        "sensor, ingestion, spoofing, or behavioral cause."
    )


def guard_cached_report(report: str | None, case: dict, threshold: float) -> str | None:
    """Apply deterministic safety language to legacy cached reports at bundle time."""
    if case.get("behavioral_verdict") != "reviewable":
        return abstention_report(case, threshold)
    if not report:
        return None
    guarded = re.sub(
        r"Genuine LEMD anomaly, not a data artifact\.",
        "Reviewable model flag; behavioral interpretation requires analyst review.",
        report,
        flags=re.IGNORECASE,
    )
    guarded = re.sub(
        r"\bgenuine LEMD anomaly\b",
        "reviewable model flag",
        guarded,
        flags=re.IGNORECASE,
    )
    return guarded


def _channel_summary(values: list[float]) -> dict:
    if not values:
        return {}
    return {"start": round(values[0], 1), "end": round(values[-1], 1),
            "min": round(min(values), 1), "max": round(max(values), 1)}


def build_context(case: dict, threshold: float, step_threshold: float) -> dict:
    """Compact, bounded context from a baked case — channel *summaries* (not full arrays) so
    token cost can't spike with segment length (codex outside-voice). Pure + unit-testable."""
    ch = case.get("channels", {})
    attribution = dict(sorted(case.get("feature_attribution", {}).items(),
                              key=lambda kv: kv[1], reverse=True))
    scores = case.get("step_scores", [])
    return {
        "segment_id": case.get("segment_id"),
        "category_label": case.get("label"),
        "data_quality": classify(case),
        "assessment_state": case.get("assessment_state"),
        "behavioral_verdict": case.get("behavioral_verdict"),
        "review_lane": case.get("review_lane"),
        "data_quality_flags": case.get("data_quality_flags", []),
        "assessment_explanation": assessment_copy(case),
        "observed_fraction": case.get("observed_fraction"),
        "max_altitude_jump_m": case.get("max_altitude_jump_m"),
        "max_implied_vertical_rate_mps": case.get("max_implied_vertical_rate_mps"),
        "max_implied_ground_speed_mps": case.get("max_implied_ground_speed_mps"),
        "score": case.get("score"),
        "threshold": threshold,
        "flagged": case.get("anomalous"),
        "percentile": case.get("pct"),
        "band": case.get("band"),
        "n_steps_total": case.get("n_steps"),
        "n_steps_scored": case.get("valid_steps"),
        "truncated": case.get("truncated"),
        "is_lemd_terminal_op": case.get("terminal_op"),
        "trajectory_segments_in_flight": case.get("n_siblings"),
        "feature_attribution_ranked": {k: round(v, 4) for k, v in attribution.items()},
        "channel_summaries": {name: _channel_summary(ch.get(name, [])) for name in ch},
        "per_step_RE_peak": round(max(scores), 4) if scores else None,
        "step_threshold": step_threshold,
    }


def generate_report(client, case: dict, threshold: float, step_threshold: float,
                    model: str) -> str:
    """One Anthropic call (build-time). System prompt is prompt-cached so a 250-case sweep
    pays for it once. Returns plain text. Raises on API error (caller decides)."""
    ctx = build_context(case, threshold, step_threshold)
    msg = client.messages.create(
        model=model,
        max_tokens=MAX_TOKENS,
        system=[{"type": "text", "text": SYSTEM_PROMPT,
                 "cache_control": {"type": "ephemeral"}}],
        messages=[{"role": "user",
                   "content": "Flight facts (JSON):\n" + json.dumps(ctx, indent=2)}],
    )
    return "".join(b.text for b in msg.content if getattr(b, "type", None) == "text").strip()


def make_client():
    """Anthropic client from ANTHROPIC_API_KEY, or None if unset (offline build skips reports)."""
    if not os.environ.get("ANTHROPIC_API_KEY"):
        return None
    import anthropic
    return anthropic.Anthropic()


def model_name() -> str:
    return os.environ.get("ANTHROPIC_MODEL", DEFAULT_MODEL)
